language: go

go:
  - "1.12"
  - "master"

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

install:
  - go get
  - go install
  - GO111MODULE=auto go get github.com/tsaikd/KDGoLib/errutil
  - GO111MODULE=auto go install ./checkerror/vendor/...
  - gobuilder version -c ">=0.1.9" &>/dev/null || go get -u -v "github.com/tsaikd/gobuilder"

script:
  - gobuilder --check --test --all
